-- Execute este SQL no Supabase:
-- Supabase > SQL Editor > New query > cole tudo > Run

create table if not exists public.ganhos (
  id bigint generated by default as identity primary key,
  descricao text not null,
  valor numeric not null,
  data date not null,
  tipo text not null,
  criado_em timestamp with time zone default now()
);

create table if not exists public.gastos (
  id bigint generated by default as identity primary key,
  descricao text not null,
  valor numeric not null,
  data date not null,
  categoria text not null,
  criado_em timestamp with time zone default now()
);

create table if not exists public.investimentos (
  id bigint generated by default as identity primary key,
  descricao text not null,
  valor numeric not null,
  data date not null,
  tipo text not null,
  objetivo text,
  criado_em timestamp with time zone default now()
);

create table if not exists public.configuracoes (
  id bigint generated by default as identity primary key,
  chave text unique not null,
  valor text not null,
  atualizado_em timestamp with time zone default now()
);

alter table public.ganhos enable row level security;
alter table public.gastos enable row level security;
alter table public.investimentos enable row level security;
alter table public.configuracoes enable row level security;

-- Regras simples para uso pessoal sem login Supabase.
-- IMPORTANTE: como é uso pessoal, não compartilhe sua chave anon public com terceiros.

drop policy if exists "permitir tudo ganhos" on public.ganhos;
create policy "permitir tudo ganhos" on public.ganhos for all using (true) with check (true);

drop policy if exists "permitir tudo gastos" on public.gastos;
create policy "permitir tudo gastos" on public.gastos for all using (true) with check (true);

drop policy if exists "permitir tudo investimentos" on public.investimentos;
create policy "permitir tudo investimentos" on public.investimentos for all using (true) with check (true);

drop policy if exists "permitir tudo configuracoes" on public.configuracoes;
create policy "permitir tudo configuracoes" on public.configuracoes for all using (true) with check (true);
