// COLE AQUI OS DADOS DO SEU PROJETO SUPABASE
// Supabase > Project Settings > API

const SUPABASE_URL = "COLE_SUA_URL_AQUI";
const SUPABASE_ANON_KEY = "COLE_SUA_CHAVE_ANON_PUBLIC_AQUI";

const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
